import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLinks from "@/app/ui/nav-links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GammaGame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-500 overflow-hidden md:overflow-auto`}>
        <main className="flex flex-col min-h-screen min-w-screen w-full items-center gap-y-5">

          <div className="relative">
            <div className="">
              <div className="flex flex-min-h-screen flex-col max-w-2xl items-center justify-center">
                {children}
              </div>
            </div>
            <div className="absolute top-0 left-0 transform">
              <div className="flex flex-col h-screen width-1/2 item-end p-1 gap-1">
                <NavLinks />
              </div>
            </div>

          </div>
        </main >
      </body>
    </html>
  );
}
