import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLinks from "@/app/ui/nav-links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GammaGame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-500`}>
        <main className="flex flex-col min-h-screen min-w-screen w-full items-center justify-center gap-y-10">
          <div className="flex flex-min-h-screen flex-col max-w-2xl items-center justify-center">
            {children}
          </div>
          <div className="flex max-w-xl items-center justify-center flex-wrap gap-3 p-3">
            <NavLinks />
          </div>
        </main >
      </body>
    </html>
  );
}
